___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__)

5.24.1

In [3]:
import cufflinks as cf

In [4]:
init_notebook_mode(connected=True)

In [5]:
cf.go_offline()

### Fake Data

In [6]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [7]:
df.head()

          A         B         C         D
0  0.133093 -0.738224 -0.771949  0.181761
1  0.200149  1.401088  0.812675  1.283725
2 -1.105640  0.232779  0.399849  0.611380
3 -1.141678 -1.134638 -0.397763 -0.154429
4 -1.015784 -0.716264 -1.158380 -0.078141

In [8]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [9]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [10]:
df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

## Bar Plots

In [11]:
df2.iplot(kind='bar',x='Category',y='Values')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [12]:
df.count().iplot(kind='bar')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

## Boxplots

In [13]:
df.iplot(kind='box')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

## 3d Surface

In [14]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

## Spread

In [15]:
df[['A','B']].iplot(kind='spread')

c:\Users\Rushil Jivan\AppData\Local\Python\pythoncore-3.11-64\Lib\site-packages\cufflinks\plotlytools.py:848: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

AttributeError: module 'pandas' has no attribute 'np'

## histogram

In [16]:
df['A'].iplot(kind='hist',bins=25)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [17]:
df.iplot(kind='bubble',x='A',y='B',size='C')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

## scatter_matrix()

Similar to sns.pairplot()

In [18]:
df.scatter_matrix()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

# Great Job!